In [2]:
import pandas as pd
import numpy as np
import datetime as dt
import requests
# import gmaps
import os
# Import API key
from api_keys import g_key

In [2]:
#data_add = '202012-citibike-tripdata.csv'
#citi_data = pd.read_csv(data_add)
#del citi_data['Unnamed: 0']
#citi_data

In [78]:
citidec_data = pd.read_csv('202011-citibike-tripdata.csv')
citidec_data

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,521,2020-11-01 00:00:07.0150,2020-11-01 00:08:48.3010,3467,W Broadway & Spring St,40.724947,-74.001659,350,Clinton St & Grand St,40.715595,-73.987030,40405,Subscriber,1989,1
1,492,2020-11-01 00:00:10.8080,2020-11-01 00:08:23.3170,3557,40 Ave & 9 St,40.757420,-73.945133,3557,40 Ave & 9 St,40.757420,-73.945133,46504,Subscriber,1970,2
2,1979,2020-11-01 00:00:14.7040,2020-11-01 00:33:14.1640,3085,Roebling St & N 4 St,40.714690,-73.957390,3854,Morgan Ave & Maspeth Ave,40.716657,-73.936370,37452,Subscriber,1989,2
3,2382,2020-11-01 00:00:14.7070,2020-11-01 00:39:57.0030,3783,Cliff St & Fulton St,40.708380,-74.004950,3167,Amsterdam Ave & W 73 St,40.779668,-73.980930,40417,Subscriber,1981,1
4,166,2020-11-01 00:00:15.9690,2020-11-01 00:03:02.8980,422,W 59 St & 10 Ave,40.770513,-73.988038,3175,W 70 St & Amsterdam Ave,40.777480,-73.982886,35776,Subscriber,1990,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1736699,257,2020-11-30 23:58:44.6840,2020-12-01 00:03:01.9470,324,DeKalb Ave & Hudson Ave,40.689888,-73.981013,421,Clermont Ave & Park Ave,40.695734,-73.971297,49932,Subscriber,1992,1
1736700,617,2020-11-30 23:58:45.6210,2020-12-01 00:09:02.8300,439,E 4 St & 2 Ave,40.726281,-73.989780,3709,W 15 St & 6 Ave,40.738046,-73.996430,38817,Customer,1969,0
1736701,116,2020-11-30 23:58:45.7200,2020-12-01 00:00:41.9570,3616,Steinway St & 28 Ave,40.765625,-73.913669,3600,31 Ave & Steinway St,40.761149,-73.917007,32874,Subscriber,1980,1
1736702,409,2020-11-30 23:59:20.1480,2020-12-01 00:06:09.7540,3521,Lenox Ave & W 111 St,40.798786,-73.952300,3325,E 95 St & 3 Ave,40.784903,-73.950503,36675,Customer,2001,1
1736703,301,2020-11-30 23:59:47.9750,2020-12-01 00:04:49.2260,241,DeKalb Ave & S Portland Ave,40.689810,-73.974931,274,Lafayette Ave & Fort Greene Pl,40.686919,-73.976682,27784,Subscriber,1948,1

In [79]:
zip_citi = citidec_data.drop_duplicates(subset=['start station name'])
zip_citi

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,521,2020-11-01 00:00:07.0150,2020-11-01 00:08:48.3010,3467,W Broadway & Spring St,40.724947,-74.001659,350,Clinton St & Grand St,40.715595,-73.987030,40405,Subscriber,1989,1
1,492,2020-11-01 00:00:10.8080,2020-11-01 00:08:23.3170,3557,40 Ave & 9 St,40.757420,-73.945133,3557,40 Ave & 9 St,40.757420,-73.945133,46504,Subscriber,1970,2
2,1979,2020-11-01 00:00:14.7040,2020-11-01 00:33:14.1640,3085,Roebling St & N 4 St,40.714690,-73.957390,3854,Morgan Ave & Maspeth Ave,40.716657,-73.936370,37452,Subscriber,1989,2
3,2382,2020-11-01 00:00:14.7070,2020-11-01 00:39:57.0030,3783,Cliff St & Fulton St,40.708380,-74.004950,3167,Amsterdam Ave & W 73 St,40.779668,-73.980930,40417,Subscriber,1981,1
4,166,2020-11-01 00:00:15.9690,2020-11-01 00:03:02.8980,422,W 59 St & 10 Ave,40.770513,-73.988038,3175,W 70 St & Amsterdam Ave,40.777480,-73.982886,35776,Subscriber,1990,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
735755,751,2020-11-11 11:50:52.8650,2020-11-11 12:03:24.1920,3459,E 53 St & 3 Ave,40.757632,-73.969306,461,E 20 St & 2 Ave,40.735877,-73.982050,44243,Subscriber,1987,1
851348,827,2020-11-14 07:38:00.9520,2020-11-14 07:51:48.8890,4232,6 Ave & W 45 St,40.756951,-73.982631,3738,Delancey St & Eldridge St,40.719383,-73.991479,36325,Customer,1998,2
1385111,246,2020-11-23 13:09:17.5410,2020-11-23 13:13:23.8620,4118,Liberty St & Nassau St,40.708589,-74.009355,417,Barclay St & Church St,40.712912,-74.010202,33754,Subscriber,1969,2
1405739,167,2020-11-23 18:32:45.7400,2020-11-23 18:35:33.2190,4219,W 35 St & 9 Ave,40.754145,-73.996089,492,W 33 St & 7 Ave,40.750200,-73.990931,49376,Customer,1995,1
1729801,454,2020-11-30 18:18:23.8250,2020-11-30 18:25:58.7140,3515,24 Ave & 26 St,40.774591,-73.918544,3592,Crescent St & Broadway,40.763359,-73.928647,41562,Subscriber,1975,1

In [80]:
zip_data = pd.read_csv('zip_code_file.csv')
stations = zip_data['start station name']
for station in stations: 
    zip_citi = zip_citi[zip_citi['start station name'] != station]
zip_citi

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
15896,1118,2020-11-01 11:32:11.0790,2020-11-01 11:50:49.3730,4150,E 170 St & Webster Ave_old,40.836103,-73.907199,4205,Crotona Park North & Prospect Ave,40.841092,-73.892317,39371,Customer,1986,1

In [18]:
station = 'Lexington Ave & E 24 St'
zip_citi = zip_citi[zip_citi['start station name'] != station]
zip_citi

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,694,2020-12-01 00:00:03.7770,2020-12-01 00:11:38.3160,4065,Wadsworth Ave & W 179 St,40.848467,-73.936064,3959,Edgecombe Ave & W 145 St,40.823498,-73.943860,49454,Customer,1988,2
1,199,2020-12-01 00:01:58.2610,2020-12-01 00:05:17.8910,4120,E 39 St & Lexington Ave,40.749499,-73.977292,3707,Lexington Ave & E 26 St,40.741459,-73.983293,36679,Subscriber,1976,1
2,138,2020-12-01 00:02:03.9160,2020-12-01 00:04:22.9040,4139,Tinton Ave & E 165 St,40.824796,-73.902420,3985,E 160 St & Tinton Ave,40.820302,-73.903944,39516,Subscriber,1988,1
3,1396,2020-12-01 00:03:15.3130,2020-12-01 00:26:32.3010,4106,Ogden Ave & W 164 St,40.832812,-73.929372,3994,2 Ave & E 125 St,40.802554,-73.933509,37343,Customer,1989,1
4,376,2020-12-01 00:04:47.8990,2020-12-01 00:11:04.4860,4072,W 48 St & Rockefeller Plaza,40.757936,-73.979603,457,Broadway & W 58 St,40.766953,-73.981693,28069,Subscriber,1963,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,2398,2020-12-29 15:56:24.5090,2020-12-29 16:36:23.3500,4184,Southern Blvd & E 174 St,40.836733,-73.887931,3301,Columbus Ave & W 95 St,40.791956,-73.968087,49446,Subscriber,1997,1
201,346,2020-12-30 13:41:42.0120,2020-12-30 13:47:28.1560,4306,35 St & 23 Ave,40.773015,-73.911190,3516,31 St & Astoria Blvd,40.769918,-73.918406,48763,Subscriber,1990,1
202,367,2020-12-31 11:18:23.6720,2020-12-31 11:24:30.7230,4328,W 167 St & St. Nicholas Ave,40.840124,-73.939490,4188,Broadway & W 155 St,40.832990,-73.945920,30336,Subscriber,1985,1
203,342,2020-12-31 12:01:46.9430,2020-12-31 12:07:29.3590,4310,24 St & 38 Ave,40.756351,-73.936515,3586,34 Ave & 13 St,40.763875,-73.936485,46577,Subscriber,1986,1
204,318,2020-12-31 20:17:25.1670,2020-12-31 20:22:43.9950,4332,Morris Ave & E 163 St,40.827230,-73.917656,4169,Morris Ave & E 171 St,40.838990,-73.910900,48231,Subscriber,1984,2

In [15]:
del zip_citi['index']
zip_citi

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,694,2020-12-01 00:00:03.7770,2020-12-01 00:11:38.3160,4065,Wadsworth Ave & W 179 St,40.848467,-73.936064,3959,Edgecombe Ave & W 145 St,40.823498,-73.943860,49454,Customer,1988,2
1,199,2020-12-01 00:01:58.2610,2020-12-01 00:05:17.8910,4120,E 39 St & Lexington Ave,40.749499,-73.977292,3707,Lexington Ave & E 26 St,40.741459,-73.983293,36679,Subscriber,1976,1
2,138,2020-12-01 00:02:03.9160,2020-12-01 00:04:22.9040,4139,Tinton Ave & E 165 St,40.824796,-73.902420,3985,E 160 St & Tinton Ave,40.820302,-73.903944,39516,Subscriber,1988,1
3,1396,2020-12-01 00:03:15.3130,2020-12-01 00:26:32.3010,4106,Ogden Ave & W 164 St,40.832812,-73.929372,3994,2 Ave & E 125 St,40.802554,-73.933509,37343,Customer,1989,1
4,376,2020-12-01 00:04:47.8990,2020-12-01 00:11:04.4860,4072,W 48 St & Rockefeller Plaza,40.757936,-73.979603,457,Broadway & W 58 St,40.766953,-73.981693,28069,Subscriber,1963,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,2398,2020-12-29 15:56:24.5090,2020-12-29 16:36:23.3500,4184,Southern Blvd & E 174 St,40.836733,-73.887931,3301,Columbus Ave & W 95 St,40.791956,-73.968087,49446,Subscriber,1997,1
201,346,2020-12-30 13:41:42.0120,2020-12-30 13:47:28.1560,4306,35 St & 23 Ave,40.773015,-73.911190,3516,31 St & Astoria Blvd,40.769918,-73.918406,48763,Subscriber,1990,1
202,367,2020-12-31 11:18:23.6720,2020-12-31 11:24:30.7230,4328,W 167 St & St. Nicholas Ave,40.840124,-73.939490,4188,Broadway & W 155 St,40.832990,-73.945920,30336,Subscriber,1985,1
203,342,2020-12-31 12:01:46.9430,2020-12-31 12:07:29.3590,4310,24 St & 38 Ave,40.756351,-73.936515,3586,34 Ave & 13 St,40.763875,-73.936485,46577,Subscriber,1986,1
204,318,2020-12-31 20:17:25.1670,2020-12-31 20:22:43.9950,4332,Morris Ave & E 163 St,40.827230,-73.917656,4169,Morris Ave & E 171 St,40.838990,-73.910900,48231,Subscriber,1984,2

In [81]:
# https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input=Museum%20of%20Contemporary%20Art%20Australia&inputtype=textquery&fields=photos,formatted_address,name,rating,opening_hours,geometry&key=YOUR_API_KEY
# https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=-33.8670522,151.1957362&radius=1500&type=restaurant&keyword=cruise&key=YOUR_API_KEY
#Create empty list to hold all of the hotel data
zip_list = []

#Format API request
stations = zip_citi['start station name']
#stations = ['E 16 St & Irving Pl', 'West St & Chambers St']
#url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?"
url = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json?"

#Print header for API processing log
print('Beginning Data Retrieval ') 
print('-----------------------------')

#Conduct a series of successive API calls to gather zipcode data for vacation cities
for station in stations: 
    print(f'Retrieving Results for Station | {station}') 
    df = zip_citi[zip_citi['start station name'] == station] 
    station_lat = df.iloc[0]['start station latitude'] 
    station_lng = df.iloc[0]['start station longitude'] 
    # parameters = (f"location={station_lat},{station_lng}&radius=50&key={g_key}")
    parameters = (f"input=Citi%20Bike&inputtype=textquery&locationbias=point:{station_lat},{station_lng}&fields=formatted_address&key={g_key}")

#Check to make sure the city has hotel data, if not skip that city and continue
    try:

#Get the response from the API request and capture the hotel data values from the request
        response = requests.get(url + parameters).json()  ###Clear this to run the api query###
        print(response)
#extract results
        address = response['candidates'][0]['formatted_address']
        print(f"Address is {address}.")
        arr = address.split(", ")
        zippy = arr[2].split(" ")
        zip = zippy[1]
        zip_list.append(zip)

#Generate an exception message if hotel data not found
    except Exception:
        print(f'{station} station not found. Skipping...')
        
zip_citi['zip code'] = zip_list
zip_citi
#zip_list

Beginning Data Retrieval
-----------------------------
Retrieving Results for Station | E 170 St & Webster Ave_old
{'candidates': [{'formatted_address': 'E 170 St & Webster Ave, The Bronx, NY 10456, United States'}], 'status': 'OK'}
Address is E 170 St & Webster Ave, The Bronx, NY 10456, United States.

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,zip code
15896,1118,2020-11-01 11:32:11.0790,2020-11-01 11:50:49.3730,4150,E 170 St & Webster Ave_old,40.836103,-73.907199,4205,Crotona Park North & Prospect Ave,40.841092,-73.892317,39371,Customer,1986,1,10456

In [82]:
print(len(zip_citi))
frames = [zip_citi, zip_data]
concat_data = pd.concat(frames).reset_index()
del concat_data['index']
print(len(concat_data))

1
1224

In [83]:
print(concat_data)

      tripduration                 starttime                  stoptime  \
0             1118  2020-11-01 11:32:11.0790  2020-11-01 11:50:49.3730
1             1049  2020-09-18 15:05:08.4850  2020-09-18 15:22:37.6330
2             1210  2020-06-26 19:11:51.1350  2020-06-26 19:32:01.8910
3              594  2020-05-01 00:05:06.1270  2020-05-01 00:15:00.6320
4             1378  2020-05-01 04:49:09.2160  2020-05-01 05:12:07.2390
...            ...                       ...                       ...
1219           334  2020-07-30 18:26:45.3910  2020-07-30 18:32:19.9200
1220          1698  2020-07-31 03:20:31.6270  2020-07-31 03:48:50.2010
1221          2736  2020-07-31 14:56:23.1100  2020-07-31 15:41:59.3750
1222          2268  2020-07-31 15:29:26.1090  2020-07-31 16:07:15.0170
1223          9810  2020-07-31 18:16:57.7300  2020-07-31 21:00:27.9700

      start station id                            start station name  \
0                 4150                    E 170 St & Webster Ave_old
1                 4151                              3 Ave & E 169 St
2                 3968                       Propsect Ave & E 151 St
3                  504         1 Ave & E 16 St [temporarily removed]
4                 3467  W Broadway & Spring St [temporarily removed]
...                ...                                           ...
1219              3976                             E 156 & Brook Ave
1220              3978                      Cauldwell Ave & E 161 St
1221              3975                          Brook Ave & E 157 St
1222              3981                    Harlem River Dr & W 155 St
1223              3977                   Prospect Ave & Longwood Ave

      start station latitude  start station longitude  end station id  \
0                  40.836103               -73.907199            4205
1                  40.832678               -73.905158            3973
2                  40.814232               -73.903927            3338
3                  40.732219               -73.981656             307
4                  40.724947               -74.001659             450
...                      ...                      ...             ...
1219               40.819823               -73.912411            3976
1220               40.821880               -73.907521            3328
1221               40.820713               -73.911759            3975
1222               40.830476               -73.939929            3314
1223               40.818990               -73.902020            3977

                       end station name  end station latitude  \
0     Crotona Park North & Prospect Ave             40.841092
1            St Nicholas Ave & W 150 St             40.827212
2                       2 Ave & E 99 St             40.786259
3                 Canal St & Rutgers St             40.714275
4                       W 49 St & 8 Ave             40.762272
...                                 ...                   ...
1219                  E 156 & Brook Ave             40.819823
1220           W 100 St & Manhattan Ave             40.795000
1221               Brook Ave & E 157 St             40.820713
1222                 W 95 St & Broadway             40.793770
1223        Prospect Ave & Longwood Ave             40.818990

      end station longitude  bikeid    usertype  birth year  gender zip code  \
0                -73.892317   39371    Customer        1986       1    10456
1                -73.942722   36801  Subscriber        1998       1    10456
2                -73.945526   38437  Subscriber        1987       1    10455
3                -73.989900   42836  Subscriber        1992       1    10009
4                -73.987882   37858    Customer        1994       1    10012
...                     ...     ...         ...         ...     ...      ...
1219             -73.912411   44111  Subscriber        1996       1    10455
1220             -73.964500   37762  Subscriber        1968       2    10456
1221             -73.911759   20010    Customer        1969       0    10451
1222             -73.971888   26150    Customer        1969       0    10032
1223             -73.902020   14657    Customer        1969       0    10459

      Unnamed: 0
0            NaN
1            0.0
2            1.0
3            2.0
4            3.0
...          ...
1219      1218.0
1220      1219.0
1221      1220.0
1222      1221.0
1223      1222.0

[1224 rows x 17 columns]

In [84]:
del concat_data['Unnamed: 0']
concat_data.to_csv("zip_code_file.csv")

In [21]:
citiJuly_data['zip code'] = 111
citiJuly_data

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,zip code
0,341,2020-07-01 00:00:01.3020,2020-07-01 00:05:42.5650,3463,E 16 St & Irving Pl,40.735367,-73.987974,2003,1 Ave & E 18 St,40.733812,-73.980544,33861,Subscriber,1986,1,111
1,321,2020-07-01 00:00:01.3620,2020-07-01 00:05:22.9490,3463,E 16 St & Irving Pl,40.735367,-73.987974,2003,1 Ave & E 18 St,40.733812,-73.980544,31233,Subscriber,1990,2,111
2,2710,2020-07-01 00:00:06.6290,2020-07-01 00:45:17.3410,426,West St & Chambers St,40.717548,-74.013221,212,W 16 St & The High Line,40.743349,-74.006818,40329,Customer,1969,0,111
3,2685,2020-07-01 00:00:13.0220,2020-07-01 00:44:58.8640,426,West St & Chambers St,40.717548,-74.013221,212,W 16 St & The High Line,40.743349,-74.006818,17567,Subscriber,1998,1,111
4,191,2020-07-01 00:00:13.4660,2020-07-01 00:03:24.6230,3615,44 Dr & 21 St,40.748000,-73.946093,3127,9 St & 44 Rd,40.749660,-73.952100,43421,Subscriber,1992,1,111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105803,877,2020-07-31 23:59:48.9250,2020-08-01 00:14:26.2540,217,Old Fulton St,40.702772,-73.993836,398,Atlantic Ave & Furman St,40.691652,-73.999979,44073,Customer,1969,0,111
2105804,839,2020-07-31 23:59:51.7740,2020-08-01 00:13:50.9750,4044,8 Ave & W 38 St,40.754610,-73.991770,3163,Central Park West & W 68 St,40.773407,-73.977825,41797,Customer,2002,1,111
2105805,1042,2020-07-31 23:59:56.1460,2020-08-01 00:17:18.5090,3723,Cadman Plaza E & Johnson St,40.695317,-73.990157,350,Clinton St & Grand St,40.715595,-73.987030,24808,Subscriber,1974,1,111
2105806,699,2020-07-31 23:59:57.4310,2020-08-01 00:11:36.5420,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,504,1 Ave & E 16 St,40.732219,-73.981656,41486,Subscriber,1991,1,111
2105807,249,2020-07-31 23:59:58.7260,2020-08-01 00:04:08.2070,446,W 24 St & 7 Ave,40.744876,-73.995299,3259,9 Ave & W 28 St,40.749370,-73.999234,28699,Customer,1990,1,111

In [34]:
for station in stations:
    df = zip_citi[zip_citi['start station name'] == station]
    zip_data = df.iloc[0]['zip code'] 
    citiJuly_data.loc[(citiJuly_data['start station name'] == station), 'zip code'] = zip_data
 #   for row in citiJuly_data:
 #       print(citiJuly_data['start station name'])
  #      if citiJuly_data['start station name'] == station:
  #          citiJuly_data['zip code'] = zip_data
print (citiJuly_data)

         tripduration                 starttime                  stoptime  \
0                 341  2020-07-01 00:00:01.3020  2020-07-01 00:05:42.5650
1                 321  2020-07-01 00:00:01.3620  2020-07-01 00:05:22.9490
2                2710  2020-07-01 00:00:06.6290  2020-07-01 00:45:17.3410
3                2685  2020-07-01 00:00:13.0220  2020-07-01 00:44:58.8640
4                 191  2020-07-01 00:00:13.4660  2020-07-01 00:03:24.6230
...               ...                       ...                       ...
2105803           877  2020-07-31 23:59:48.9250  2020-08-01 00:14:26.2540
2105804           839  2020-07-31 23:59:51.7740  2020-08-01 00:13:50.9750
2105805          1042  2020-07-31 23:59:56.1460  2020-08-01 00:17:18.5090
2105806           699  2020-07-31 23:59:57.4310  2020-08-01 00:11:36.5420
2105807           249  2020-07-31 23:59:58.7260  2020-08-01 00:04:08.2070

         start station id           start station name  \
0                    3463          E 16 St & Irving Pl
1                    3463          E 16 St & Irving Pl
2                     426        West St & Chambers St
3                     426        West St & Chambers St
4                    3615                44 Dr & 21 St
...                   ...                          ...
2105803               217                Old Fulton St
2105804              4044              8 Ave & W 38 St
2105805              3723  Cadman Plaza E & Johnson St
2105806               161        LaGuardia Pl & W 3 St
2105807               446              W 24 St & 7 Ave

         start station latitude  start station longitude  end station id  \
0                     40.735367               -73.987974            2003
1                     40.735367               -73.987974            2003
2                     40.717548               -74.013221             212
3                     40.717548               -74.013221             212
4                     40.748000               -73.946093            3127
...                         ...                      ...             ...
2105803               40.702772               -73.993836             398
2105804               40.754610               -73.991770            3163
2105805               40.695317               -73.990157             350
2105806               40.729170               -73.998102             504
2105807               40.744876               -73.995299            3259

                    end station name  end station latitude  \
0                    1 Ave & E 18 St             40.733812
1                    1 Ave & E 18 St             40.733812
2            W 16 St & The High Line             40.743349
3            W 16 St & The High Line             40.743349
4                       9 St & 44 Rd             40.749660
...                              ...                   ...
2105803     Atlantic Ave & Furman St             40.691652
2105804  Central Park West & W 68 St             40.773407
2105805        Clinton St & Grand St             40.715595
2105806              1 Ave & E 16 St             40.732219
2105807              9 Ave & W 28 St             40.749370

         end station longitude  bikeid    usertype  birth year  gender  \
0                   -73.980544   33861  Subscriber        1986       1
1                   -73.980544   31233  Subscriber        1990       2
2                   -74.006818   40329    Customer        1969       0
3                   -74.006818   17567  Subscriber        1998       1
4                   -73.952100   43421  Subscriber        1992       1
...                        ...     ...         ...         ...     ...
2105803             -73.999979   44073    Customer        1969       0
2105804             -73.977825   41797    Customer        2002       1
2105805             -73.987030   24808  Subscriber        1974       1
2105806             -73.981656   41486  Subscriber        1991       1
2105807             -73.999234   28699    Customer        1990       1

        zip code
0          10003
1          10003
2          10282
3          10282
4          11101
...          ...
2105803    11201
2105804    10018
2105805    11201
2105806    10012
2105807    10011

[2105808 rows x 16 columns]

In [35]:
citiJuly_data.to_csv("2007_data.csv")

In [56]:
citi2007_data = pd.read_csv('2007_data.csv')
print(citi2007_data)
print(citi2007_data.describe())

         Unnamed: 0  tripduration                 starttime  \
0                 0           341  2020-07-01 00:00:01.3020
1                 1           321  2020-07-01 00:00:01.3620
2                 2          2710  2020-07-01 00:00:06.6290
3                 3          2685  2020-07-01 00:00:13.0220
4                 4           191  2020-07-01 00:00:13.4660
...             ...           ...                       ...
2105803     2105803           877  2020-07-31 23:59:48.9250
2105804     2105804           839  2020-07-31 23:59:51.7740
2105805     2105805          1042  2020-07-31 23:59:56.1460
2105806     2105806           699  2020-07-31 23:59:57.4310
2105807     2105807           249  2020-07-31 23:59:58.7260

                         stoptime  start station id  \
0        2020-07-01 00:05:42.5650              3463
1        2020-07-01 00:05:22.9490              3463
2        2020-07-01 00:45:17.3410               426
3        2020-07-01 00:44:58.8640               426
4        2020-07-01 00:03:24.6230              3615
...                           ...               ...
2105803  2020-08-01 00:14:26.2540               217
2105804  2020-08-01 00:13:50.9750              4044
2105805  2020-08-01 00:17:18.5090              3723
2105806  2020-08-01 00:11:36.5420               161
2105807  2020-08-01 00:04:08.2070               446

                  start station name  start station latitude  \
0                E 16 St & Irving Pl               40.735367
1                E 16 St & Irving Pl               40.735367
2              West St & Chambers St               40.717548
3              West St & Chambers St               40.717548
4                      44 Dr & 21 St               40.748000
...                              ...                     ...
2105803                Old Fulton St               40.702772
2105804              8 Ave & W 38 St               40.754610
2105805  Cadman Plaza E & Johnson St               40.695317
2105806        LaGuardia Pl & W 3 St               40.729170
2105807              W 24 St & 7 Ave               40.744876

         start station longitude  end station id             end station name  \
0                     -73.987974            2003              1 Ave & E 18 St
1                     -73.987974            2003              1 Ave & E 18 St
2                     -74.013221             212      W 16 St & The High Line
3                     -74.013221             212      W 16 St & The High Line
4                     -73.946093            3127                 9 St & 44 Rd
...                          ...             ...                          ...
2105803               -73.993836             398     Atlantic Ave & Furman St
2105804               -73.991770            3163  Central Park West & W 68 St
2105805               -73.990157             350        Clinton St & Grand St
2105806               -73.998102             504              1 Ave & E 16 St
2105807               -73.995299            3259              9 Ave & W 28 St

         end station latitude  end station longitude  bikeid    usertype  \
0                   40.733812             -73.980544   33861  Subscriber
1                   40.733812             -73.980544   31233  Subscriber
2                   40.743349             -74.006818   40329    Customer
3                   40.743349             -74.006818   17567  Subscriber
4                   40.749660             -73.952100   43421  Subscriber
...                       ...                    ...     ...         ...
2105803             40.691652             -73.999979   44073    Customer
2105804             40.773407             -73.977825   41797    Customer
2105805             40.715595             -73.987030   24808  Subscriber
2105806             40.732219             -73.981656   41486  Subscriber
2105807             40.749370             -73.999234   28699    Customer

         birth year  gender zip code
0              1986       1    10003
1              1990       2    10003
2              1969       0    10282
3              1998       1    10282
4              1992       1    11101
...             ...     ...      ...
2105803        1969       0    11201
2105804        2002       1    10018
2105805        1974       1    11201
2105806        1991       1    10012
2105807        1990       1    10011

[2105808 rows x 17 columns]
         Unnamed: 0  tripduration  start station id  start station latitude  \
count  2.105808e+06  2.105808e+06      2.105808e+06            2.105808e+06
mean   1.052904e+06  1.587440e+03      2.054467e+03            4.074029e+01
std    6.078946e+05  2.127774e+04      1.536265e+03            3.507676e-02
min    0.000000e+00  6.100000e+01      7.200000e+01            4.065540e+01
25%    5.264518e+05  4.770000e+02      4.260000e+02            4.071606e+01
50%    1.052904e+06  8.780000e+02      3.092000e+03            4.073936e+01
75%    1.579355e+06  1.523000e+03      3.469000e+03            4.076391e+01
max    2.105807e+06  3.522382e+06      4.064000e+03            4.084284e+01

       start station longitude  end station id  end station latitude  \
count             2.105808e+06    2.105808e+06          2.105808e+06
mean             -7.397635e+01    2.046171e+03          4.073983e+01
std               2.354355e-02    1.537859e+03          3.499878e-02
min              -7.402535e+01    7.200000e+01          4.065540e+01
25%              -7.399392e+01    4.260000e+02          4.071582e+01
50%              -7.398069e+01    3.085000e+03          4.073902e+01
75%              -7.395939e+01    3.469000e+03          4.076360e+01
max              -7.389795e+01    4.064000e+03          4.084284e+01

       end station longitude        bikeid    birth year        gender
count           2.105808e+06  2.105808e+06  2.105808e+06  2.105808e+06
mean           -7.397654e+01  3.428714e+04  1.981506e+03  1.171341e+00
std             2.363230e-02  9.005630e+03  1.219202e+01  6.331304e-01
min            -7.406860e+01  1.452900e+04  1.873000e+03  0.000000e+00
25%            -7.399393e+01  2.838300e+04  1.969000e+03  1.000000e+00
50%            -7.398101e+01  3.761400e+04  1.985000e+03  1.000000e+00
75%            -7.395939e+01  4.172300e+04  1.991000e+03  2.000000e+00
max            -7.389795e+01  4.565000e+04  2.004000e+03  2.000000e+00

In [57]:
#print (citi2007_data["tripduration"].mean())
#print (citi2007_data["tripduration"].median())
#print (citi2007_data.agg({"tripduration": ["min", "max", "mean", "median", "skew"]}))

In [58]:
#print (type(citi2007_data.iloc[0]['starttime']))
citi2007_data['timestamp'] = citi2007_data['starttime'].apply(lambda x : pd.to_datetime(str(x)))
#date = citi2007_data.iloc[0]['starttime'].dt.date
#citi2007_data['dates'] = citi2007_data['starttime'].dt.date
#citi2007_data['Year'] = [dt.datetime.date(Y) for Y in citi2007_data['timestamp']] 
#citi2007_data['Month'] = [dt.datetime.date(m) for m in citi2007_data['timestamp']]
#citi2007_data['Day'] = [dt.datetime.date(d) for d in citi2007_data['timestamp']]
print(citi2007_data)
#citi2007_data[["tripduration", "zip code"]].groupby(citi2007_data["start station name"]).agg({"tripduration": ["count", "sum", "min", "max", "mean", "median", "skew"], "zip code": ["first"]})
#citi2007_data[["tripduration", "zip code"]].groupby(citi2007_data["start station name"]).mean()

         Unnamed: 0  tripduration                 starttime  \
0                 0           341  2020-07-01 00:00:01.3020
1                 1           321  2020-07-01 00:00:01.3620
2                 2          2710  2020-07-01 00:00:06.6290
3                 3          2685  2020-07-01 00:00:13.0220
4                 4           191  2020-07-01 00:00:13.4660
...             ...           ...                       ...
2105803     2105803           877  2020-07-31 23:59:48.9250
2105804     2105804           839  2020-07-31 23:59:51.7740
2105805     2105805          1042  2020-07-31 23:59:56.1460
2105806     2105806           699  2020-07-31 23:59:57.4310
2105807     2105807           249  2020-07-31 23:59:58.7260

                         stoptime  start station id  \
0        2020-07-01 00:05:42.5650              3463
1        2020-07-01 00:05:22.9490              3463
2        2020-07-01 00:45:17.3410               426
3        2020-07-01 00:44:58.8640               426
4        2020-07-01 00:03:24.6230              3615
...                           ...               ...
2105803  2020-08-01 00:14:26.2540               217
2105804  2020-08-01 00:13:50.9750              4044
2105805  2020-08-01 00:17:18.5090              3723
2105806  2020-08-01 00:11:36.5420               161
2105807  2020-08-01 00:04:08.2070               446

                  start station name  start station latitude  \
0                E 16 St & Irving Pl               40.735367
1                E 16 St & Irving Pl               40.735367
2              West St & Chambers St               40.717548
3              West St & Chambers St               40.717548
4                      44 Dr & 21 St               40.748000
...                              ...                     ...
2105803                Old Fulton St               40.702772
2105804              8 Ave & W 38 St               40.754610
2105805  Cadman Plaza E & Johnson St               40.695317
2105806        LaGuardia Pl & W 3 St               40.729170
2105807              W 24 St & 7 Ave               40.744876

         start station longitude  end station id             end station name  \
0                     -73.987974            2003              1 Ave & E 18 St
1                     -73.987974            2003              1 Ave & E 18 St
2                     -74.013221             212      W 16 St & The High Line
3                     -74.013221             212      W 16 St & The High Line
4                     -73.946093            3127                 9 St & 44 Rd
...                          ...             ...                          ...
2105803               -73.993836             398     Atlantic Ave & Furman St
2105804               -73.991770            3163  Central Park West & W 68 St
2105805               -73.990157             350        Clinton St & Grand St
2105806               -73.998102             504              1 Ave & E 16 St
2105807               -73.995299            3259              9 Ave & W 28 St

         end station latitude  end station longitude  bikeid    usertype  \
0                   40.733812             -73.980544   33861  Subscriber
1                   40.733812             -73.980544   31233  Subscriber
2                   40.743349             -74.006818   40329    Customer
3                   40.743349             -74.006818   17567  Subscriber
4                   40.749660             -73.952100   43421  Subscriber
...                       ...                    ...     ...         ...
2105803             40.691652             -73.999979   44073    Customer
2105804             40.773407             -73.977825   41797    Customer
2105805             40.715595             -73.987030   24808  Subscriber
2105806             40.732219             -73.981656   41486  Subscriber
2105807             40.749370             -73.999234   28699    Customer

         birth year  gender zip code               timestamp
0              1986       1    10003 2020-07-01 00:00:01.302
1              1990       2    10003 2020-07-01 00:00:01.362
2              1969       0    10282 2020-07-01 00:00:06.629
3              1998       1    10282 2020-07-01 00:00:13.022
4              1992       1    11101 2020-07-01 00:00:13.466
...             ...     ...      ...                     ...
2105803        1969       0    11201 2020-07-31 23:59:48.925
2105804        2002       1    10018 2020-07-31 23:59:51.774
2105805        1974       1    11201 2020-07-31 23:59:56.146
2105806        1991       1    10012 2020-07-31 23:59:57.431
2105807        1990       1    10011 2020-07-31 23:59:58.726

[2105808 rows x 18 columns]

In [59]:
citi2007_data['date'] = [dt.datetime.date(d) for d in citi2007_data['timestamp']]
citi2007_data['month'] = pd.DatetimeIndex(citi2007_data['timestamp']).month

In [62]:
citi2007_data['year'] = pd.DatetimeIndex(citi2007_data['timestamp']).year
citi2007_data

,Unnamed: 0,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,...,end station longitude,bikeid,usertype,birth year,gender,zip code,timestamp,date,month,year
0,0,341,2020-07-01 00:00:01.3020,2020-07-01 00:05:42.5650,3463,E 16 St & Irving Pl,40.735367,-73.987974,2003,1 Ave & E 18 St,...,-73.980544,33861,Subscriber,1986,1,10003,2020-07-01 00:00:01.302,2020-07-01,7,2020
1,1,321,2020-07-01 00:00:01.3620,2020-07-01 00:05:22.9490,3463,E 16 St & Irving Pl,40.735367,-73.987974,2003,1 Ave & E 18 St,...,-73.980544,31233,Subscriber,1990,2,10003,2020-07-01 00:00:01.362,2020-07-01,7,2020
2,2,2710,2020-07-01 00:00:06.6290,2020-07-01 00:45:17.3410,426,West St & Chambers St,40.717548,-74.013221,212,W 16 St & The High Line,...,-74.006818,40329,Customer,1969,0,10282,2020-07-01 00:00:06.629,2020-07-01,7,2020
3,3,2685,2020-07-01 00:00:13.0220,2020-07-01 00:44:58.8640,426,West St & Chambers St,40.717548,-74.013221,212,W 16 St & The High Line,...,-74.006818,17567,Subscriber,1998,1,10282,2020-07-01 00:00:13.022,2020-07-01,7,2020
4,4,191,2020-07-01 00:00:13.4660,2020-07-01 00:03:24.6230,3615,44 Dr & 21 St,40.748000,-73.946093,3127,9 St & 44 Rd,...,-73.952100,43421,Subscriber,1992,1,11101,2020-07-01 00:00:13.466,2020-07-01,7,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105803,2105803,877,2020-07-31 23:59:48.9250,2020-08-01 00:14:26.2540,217,Old Fulton St,40.702772,-73.993836,398,Atlantic Ave & Furman St,...,-73.999979,44073,Customer,1969,0,11201,2020-07-31 23:59:48.925,2020-07-31,7,2020
2105804,2105804,839,2020-07-31 23:59:51.7740,2020-08-01 00:13:50.9750,4044,8 Ave & W 38 St,40.754610,-73.991770,3163,Central Park West & W 68 St,...,-73.977825,41797,Customer,2002,1,10018,2020-07-31 23:59:51.774,2020-07-31,7,2020
2105805,2105805,1042,2020-07-31 23:59:56.1460,2020-08-01 00:17:18.5090,3723,Cadman Plaza E & Johnson St,40.695317,-73.990157,350,Clinton St & Grand St,...,-73.987030,24808,Subscriber,1974,1,11201,2020-07-31 23:59:56.146,2020-07-31,7,2020
2105806,2105806,699,2020-07-31 23:59:57.4310,2020-08-01 00:11:36.5420,161,LaGuardia Pl & W 3 St,40.729170,-73.998102,504,1 Ave & E 16 St,...,-73.981656,41486,Subscriber,1991,1,10012,2020-07-31 23:59:57.431,2020-07-31,7,2020
2105807,2105807,249,2020-07-31 23:59:58.7260,2020-08-01 00:04:08.2070,446,W 24 St & 7 Ave,40.744876,-73.995299,3259,9 Ave & W 28 St,...,-73.999234,28699,Customer,1990,1,10011,2020-07-31 23:59:58.726,2020-07-31,7,2020

In [63]:
citi2020_data = citi2007_data
citi2020_data.to_csv("2020_annual_data.csv")

In [72]:
citi_grouped = citi2020_data[["tripduration", "start station latitude", "start station longitude", "zip code", "year"]].groupby([citi2020_data["start station name"],citi2020_data["month"]]).agg({"tripduration": ["count", "sum", "min", "max", "mean", "median", "skew"], "start station latitude": ["first"], "start station longitude": ["first"], "zip code": ["first"], "year": ["first"]}).reset_index()
citi_grouped.columns = ['start station name', 'month', 'trip count', 'sum duration', 'min duration', 'max duration', 'mean duration', 'median duration', 'skew', 'start station latitude', 'start station longitude', 'zip code', 'year']
citi_grouped

,start station name,month,trip count,sum duration,min duration,max duration,mean duration,median duration,skew,start station latitude,start station longitude,zip code,year
0,1 Ave & E 110 St,7,2046,2946989,63,46202,1440.366080,967.0,10.012117,40.792327,-73.938300,10029,2020
1,1 Ave & E 16 St,7,6138,6361457,62,274460,1036.405507,654.0,48.372820,40.732219,-73.981656,10009,2020
2,1 Ave & E 18 St,7,4690,4933137,61,236656,1051.841578,674.5,37.137321,40.733812,-73.980544,10009,2020
3,1 Ave & E 30 St,7,3853,3569653,63,38644,926.460680,723.0,16.089863,40.741444,-73.975361,10016,2020
4,1 Ave & E 44 St,7,3166,3745844,61,38158,1183.147189,958.5,12.094172,40.750020,-73.969053,10017,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,Wyckoff Av & Jefferson St,7,818,995324,76,42960,1216.777506,925.5,14.919864,40.707165,-73.923711,11237,2020
985,Wyckoff Av & Stanhope St,7,852,1287472,77,238923,1511.117371,856.5,26.115456,40.703545,-73.917775,11237,2020
986,Wyckoff St & Nevins St,7,885,1022662,62,95969,1155.550282,762.0,24.954475,40.683426,-73.984275,11217,2020
987,Wythe Ave & Metropolitan Ave,7,3750,8661778,62,1506609,2309.807467,1085.5,36.878264,40.716887,-73.963198,11249,2020
988,Yankee Ferry Terminal,7,914,1870561,61,13787,2046.565646,1709.0,3.248638,40.686931,-74.016966,11231,2020

In [73]:
citi_grouped.to_csv("2020_groupedByMonth_data.csv")

In [75]:
citi_group = pd.read_csv('2020_groupedByMonth_data.csv')
del citi_group['Unnamed: 0']
citi_group

,start station name,month,trip count,sum duration,min duration,max duration,mean duration,median duration,skew,start station latitude,start station longitude,zip code,year
0,1 Ave & E 110 St,7,2046,2946989,63,46202,1440.366080,967.0,10.012117,40.792327,-73.938300,10029,2020
1,1 Ave & E 16 St,7,6138,6361457,62,274460,1036.405507,654.0,48.372820,40.732219,-73.981656,10009,2020
2,1 Ave & E 18 St,7,4690,4933137,61,236656,1051.841578,674.5,37.137321,40.733812,-73.980544,10009,2020
3,1 Ave & E 30 St,7,3853,3569653,63,38644,926.460680,723.0,16.089863,40.741444,-73.975361,10016,2020
4,1 Ave & E 44 St,7,3166,3745844,61,38158,1183.147189,958.5,12.094172,40.750020,-73.969053,10017,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,Wyckoff Av & Jefferson St,7,818,995324,76,42960,1216.777506,925.5,14.919864,40.707165,-73.923711,11237,2020
985,Wyckoff Av & Stanhope St,7,852,1287472,77,238923,1511.117371,856.5,26.115456,40.703545,-73.917775,11237,2020
986,Wyckoff St & Nevins St,7,885,1022662,62,95969,1155.550282,762.0,24.954475,40.683426,-73.984275,11217,2020
987,Wythe Ave & Metropolitan Ave,7,3750,8661778,62,1506609,2309.807467,1085.5,36.878264,40.716887,-73.963198,11249,2020
988,Yankee Ferry Terminal,7,914,1870561,61,13787,2046.565646,1709.0,3.248638,40.686931,-74.016966,11231,2020

In [76]:
#data_sets = ['202001-citibike-tripdata.csv', '202002-citibike-tripdata.csv', '202003-citibike-tripdata.csv', '202004-citibike-tripdata.csv', '202005-citibike-tripdata.csv', '202006-citibike-tripdata.csv', '202007-citibike-tripdata.csv', '202008-citibike-tripdata.csv', '202009-citibike-tripdata.csv', '202010-citibike-tripdata.csv', '202011-citibike-tripdata.csv', '202012-citibike-tripdata.csv']
data_sets = ['202001-citibike-tripdata.csv']
for set in data_sets: 
    citibike_data = pd.read_csv(set)
#print(citi2007_data)
    print(citibike_data.describe())

       tripduration  start station id  start station latitude  \
count  1.240596e+06      1.240596e+06            1.240596e+06
mean   7.846299e+02      1.676428e+03            4.073759e+01
std    6.076151e+03      1.495895e+03            2.970666e-02
min    6.100000e+01      7.200000e+01            4.065540e+01
25%    3.230000e+02      3.850000e+02            4.071882e+01
50%    5.290000e+02      5.130000e+02            4.073913e+01
75%    8.940000e+02      3.317000e+03            4.075680e+01
max    1.952746e+06      3.918000e+03            4.081830e+01

       start station longitude  end station id  end station latitude  \
count             1.240596e+06    1.240596e+06          1.240596e+06
mean             -7.398175e+01    1.666457e+03          4.073724e+01
std               1.931888e-02    1.495605e+03          2.946039e-02
min              -7.401713e+01    7.200000e+01          4.065540e+01
25%              -7.399456e+01    3.830000e+02          4.071882e+01
50%              -7.398484e+01    5.090000e+02          4.073827e+01
75%              -7.397210e+01    3.317000e+03          4.075641e+01
max              -7.389795e+01    3.918000e+03          4.081830e+01

       end station longitude        bikeid    birth year        gender
count           1.240596e+06  1.240596e+06  1.240596e+06  1.240596e+06
mean           -7.398205e+01  3.267581e+04  1.979777e+03  1.179057e+00
std             1.940547e-02  8.057179e+03  1.242231e+01  4.887083e-01
min            -7.403548e+01  1.453000e+04  1.885000e+03  0.000000e+00
25%            -7.399468e+01  2.854700e+04  1.970000e+03  1.000000e+00
50%            -7.398565e+01  3.390200e+04  1.982000e+03  1.000000e+00
75%            -7.397283e+01  3.974800e+04  1.990000e+03  1.000000e+00
max            -7.389795e+01  4.209100e+04  2.004000e+03  2.000000e+00

In [77]:
citibike_data['timestamp'] = citibike_data['starttime'].apply(lambda x : pd.to_datetime(str(x)))
citibike_data['date'] = [dt.datetime.date(d) for d in citibike_data['timestamp']]
citibike_data['month'] = pd.DatetimeIndex(citibike_data['timestamp']).month
citibike_data['year'] = pd.DatetimeIndex(citibike_data['timestamp']).year
citibike_data

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,timestamp,date,month,year
0,789,2020-01-01 00:00:55.3900,2020-01-01 00:14:05.1470,504,1 Ave & E 16 St,40.732219,-73.981656,307,Canal St & Rutgers St,40.714275,-73.989900,30326,Subscriber,1992,1,2020-01-01 00:00:55.390,2020-01-01,1,2020
1,1541,2020-01-01 00:01:08.1020,2020-01-01 00:26:49.1780,3423,West Drive & Prospect Park West,40.661063,-73.979453,3300,Prospect Park West & 8 St,40.665147,-73.976376,17105,Customer,1969,1,2020-01-01 00:01:08.102,2020-01-01,1,2020
2,1464,2020-01-01 00:01:42.1400,2020-01-01 00:26:07.0110,3687,E 33 St & 1 Ave,40.743227,-73.974498,259,South St & Whitehall St,40.701221,-74.012342,40177,Subscriber,1963,1,2020-01-01 00:01:42.140,2020-01-01,1,2020
3,592,2020-01-01 00:01:45.5610,2020-01-01 00:11:38.1550,346,Bank St & Hudson St,40.736529,-74.006180,490,8 Ave & W 33 St,40.751551,-73.993934,27690,Subscriber,1980,1,2020-01-01 00:01:45.561,2020-01-01,1,2020
4,702,2020-01-01 00:01:45.7880,2020-01-01 00:13:28.2400,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,3637,Fulton St & Waverly Ave,40.683239,-73.965996,32583,Subscriber,1982,1,2020-01-01 00:01:45.788,2020-01-01,1,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1240591,1587,2020-01-31 23:59:26.8820,2020-02-01 00:25:54.4890,3244,University Pl & E 8 St,40.731437,-73.994903,3092,Berry St & N 8 St,40.719009,-73.958525,40662,Subscriber,1990,1,2020-01-31 23:59:26.882,2020-01-31,1,2020
1240592,222,2020-01-31 23:59:32.6410,2020-02-01 00:03:15.4720,383,Greenwich Ave & Charles St,40.735238,-74.000271,383,Greenwich Ave & Charles St,40.735238,-74.000271,28722,Subscriber,1983,1,2020-01-31 23:59:32.641,2020-01-31,1,2020
1240593,163,2020-01-31 23:59:39.1780,2020-02-01 00:02:23.0400,150,E 2 St & Avenue C,40.720874,-73.980858,411,E 6 St & Avenue D,40.722281,-73.976687,32530,Subscriber,1958,2,2020-01-31 23:59:39.178,2020-01-31,1,2020
1240594,327,2020-01-31 23:59:49.2310,2020-02-01 00:05:16.3790,483,E 12 St & 3 Ave,40.732233,-73.988900,3718,E 11 St & Avenue B,40.727464,-73.979504,15314,Customer,1994,1,2020-01-31 23:59:49.231,2020-01-31,1,2020
1240595,484,2020-01-31 23:59:57.0360,2020-02-01 00:08:01.1820,327,Vesey Pl & River Terrace,40.715338,-74.016584,534,Water - Whitehall Plaza,40.702551,-74.012723,30947,Subscriber,1987,1,2020-01-31 23:59:57.036,2020-01-31,1,2020

In [81]:
frames = [citi2020_data, citibike_data]
#del citi2020_data['Unnamed: 0']
concat_data = pd.concat(frames).reset_index()
del concat_data['index']
concat_data

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,zip code,timestamp,date,month,year
0,341,2020-07-01 00:00:01.3020,2020-07-01 00:05:42.5650,3463,E 16 St & Irving Pl,40.735367,-73.987974,2003,1 Ave & E 18 St,40.733812,-73.980544,33861,Subscriber,1986,1,10003,2020-07-01 00:00:01.302,2020-07-01,7,2020
1,321,2020-07-01 00:00:01.3620,2020-07-01 00:05:22.9490,3463,E 16 St & Irving Pl,40.735367,-73.987974,2003,1 Ave & E 18 St,40.733812,-73.980544,31233,Subscriber,1990,2,10003,2020-07-01 00:00:01.362,2020-07-01,7,2020
2,2710,2020-07-01 00:00:06.6290,2020-07-01 00:45:17.3410,426,West St & Chambers St,40.717548,-74.013221,212,W 16 St & The High Line,40.743349,-74.006818,40329,Customer,1969,0,10282,2020-07-01 00:00:06.629,2020-07-01,7,2020
3,2685,2020-07-01 00:00:13.0220,2020-07-01 00:44:58.8640,426,West St & Chambers St,40.717548,-74.013221,212,W 16 St & The High Line,40.743349,-74.006818,17567,Subscriber,1998,1,10282,2020-07-01 00:00:13.022,2020-07-01,7,2020
4,191,2020-07-01 00:00:13.4660,2020-07-01 00:03:24.6230,3615,44 Dr & 21 St,40.748000,-73.946093,3127,9 St & 44 Rd,40.749660,-73.952100,43421,Subscriber,1992,1,11101,2020-07-01 00:00:13.466,2020-07-01,7,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3346399,1587,2020-01-31 23:59:26.8820,2020-02-01 00:25:54.4890,3244,University Pl & E 8 St,40.731437,-73.994903,3092,Berry St & N 8 St,40.719009,-73.958525,40662,Subscriber,1990,1,NaN,2020-01-31 23:59:26.882,2020-01-31,1,2020
3346400,222,2020-01-31 23:59:32.6410,2020-02-01 00:03:15.4720,383,Greenwich Ave & Charles St,40.735238,-74.000271,383,Greenwich Ave & Charles St,40.735238,-74.000271,28722,Subscriber,1983,1,NaN,2020-01-31 23:59:32.641,2020-01-31,1,2020
3346401,163,2020-01-31 23:59:39.1780,2020-02-01 00:02:23.0400,150,E 2 St & Avenue C,40.720874,-73.980858,411,E 6 St & Avenue D,40.722281,-73.976687,32530,Subscriber,1958,2,NaN,2020-01-31 23:59:39.178,2020-01-31,1,2020
3346402,327,2020-01-31 23:59:49.2310,2020-02-01 00:05:16.3790,483,E 12 St & 3 Ave,40.732233,-73.988900,3718,E 11 St & Avenue B,40.727464,-73.979504,15314,Customer,1994,1,NaN,2020-01-31 23:59:49.231,2020-01-31,1,2020
3346403,484,2020-01-31 23:59:57.0360,2020-02-01 00:08:01.1820,327,Vesey Pl & River Terrace,40.715338,-74.016584,534,Water - Whitehall Plaza,40.702551,-74.012723,30947,Subscriber,1987,1,NaN,2020-01-31 23:59:57.036,2020-01-31,1,2020

In [83]:
citi_grouped = concat_data[["tripduration", "start station latitude", "start station longitude", "zip code", "year"]].groupby([concat_data["start station name"],concat_data["month"]]).agg({"tripduration": ["count", "sum", "min", "max", "mean", "median", "skew"], "start station latitude": ["first"], "start station longitude": ["first"], "zip code": ["first"], "year": ["first"]}).reset_index()
citi_grouped.columns = ['start station name', 'month', 'trip count', 'sum duration', 'min duration', 'max duration', 'mean duration', 'median duration', 'skew', 'start station latitude', 'start station longitude', 'zip code', 'year']
citi_grouped

,start station name,month,trip count,sum duration,min duration,max duration,mean duration,median duration,skew,start station latitude,start station longitude,zip code,year
0,1 Ave & E 110 St,1,689,502601,79,9774,729.464441,481.0,5.944686,40.792327,-73.938300,None,2020
1,1 Ave & E 110 St,7,2046,2946989,63,46202,1440.366080,967.0,10.012117,40.792327,-73.938300,10029,2020
2,1 Ave & E 16 St,1,4835,3101403,61,56461,641.448397,462.0,31.837229,40.732219,-73.981656,None,2020
3,1 Ave & E 16 St,7,6138,6361457,62,274460,1036.405507,654.0,48.372820,40.732219,-73.981656,10009,2020
4,1 Ave & E 18 St,1,4465,2795004,63,44125,625.980739,488.0,34.767948,40.733812,-73.980544,None,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1877,Wyckoff St & Nevins St,1,435,238456,92,3739,548.174713,429.0,2.416111,40.683426,-73.984275,None,2020
1878,Wyckoff St & Nevins St,7,885,1022662,62,95969,1155.550282,762.0,24.954475,40.683426,-73.984275,11217,2020
1879,Wythe Ave & Metropolitan Ave,1,2210,1784277,70,179846,807.365158,528.0,45.006127,40.716887,-73.963198,None,2020
1880,Wythe Ave & Metropolitan Ave,7,3750,8661778,62,1506609,2309.807467,1085.5,36.878264,40.716887,-73.963198,11249,2020
1881,Yankee Ferry Terminal,7,914,1870561,61,13787,2046.565646,1709.0,3.248638,40.686931,-74.016966,11231,2020

In [85]:
zips = pd.read_csv("zip_code_file.csv")
stations = zips['start station name']
for station in stations:
    df = zips[zips['start station name'] == station]
    zip_data = df.iloc[0]['zip code'] 
    citi_grouped.loc[(citi_grouped['start station name'] == station), 'zip code'] = zip_data
print (citi_grouped)

                start station name  month  trip count  sum duration  \
0                 1 Ave & E 110 St      1         689        502601
1                 1 Ave & E 110 St      7        2046       2946989
2                  1 Ave & E 16 St      1        4835       3101403
3                  1 Ave & E 16 St      7        6138       6361457
4                  1 Ave & E 18 St      1        4465       2795004
...                            ...    ...         ...           ...
1877        Wyckoff St & Nevins St      1         435        238456
1878        Wyckoff St & Nevins St      7         885       1022662
1879  Wythe Ave & Metropolitan Ave      1        2210       1784277
1880  Wythe Ave & Metropolitan Ave      7        3750       8661778
1881         Yankee Ferry Terminal      7         914       1870561

      min duration  max duration  mean duration  median duration       skew  \
0               79          9774     729.464441            481.0   5.944686
1               63         46202    1440.366080            967.0  10.012117
2               61         56461     641.448397            462.0  31.837229
3               62        274460    1036.405507            654.0  48.372820
4               63         44125     625.980739            488.0  34.767948
...            ...           ...            ...              ...        ...
1877            92          3739     548.174713            429.0   2.416111
1878            62         95969    1155.550282            762.0  24.954475
1879            70        179846     807.365158            528.0  45.006127
1880            62       1506609    2309.807467           1085.5  36.878264
1881            61         13787    2046.565646           1709.0   3.248638

      start station latitude  start station longitude zip code  year
0                  40.792327               -73.938300    10029  2020
1                  40.792327               -73.938300    10029  2020
2                  40.732219               -73.981656    10009  2020
3                  40.732219               -73.981656    10009  2020
4                  40.733812               -73.980544    10009  2020
...                      ...                      ...      ...   ...
1877               40.683426               -73.984275    11217  2020
1878               40.683426               -73.984275    11217  2020
1879               40.716887               -73.963198    11249  2020
1880               40.716887               -73.963198    11249  2020
1881               40.686931               -74.016966    11231  2020

[1882 rows x 13 columns]

In [86]:
citi_grouped.to_csv("2020_groupedByMonth_data.csv")

In [87]:
citibike_data.to_csv("2001_data.csv")

In [103]:
st_r = data_sets[0]
print (st_r)
x = st_r.split("-")
print (x[0])
S = x[0][0 : 2 : ] + x[0][4 : :]
print(S)
S = S +'_data.csv'
print(S)

202001-citibike-tripdata.csv
202001
2001
2001_data.csv

In [105]:
concat_data.to_csv("2020_annual_data.csv")
print(concat_data)

         tripduration                 starttime                  stoptime  \
0                 341  2020-07-01 00:00:01.3020  2020-07-01 00:05:42.5650
1                 321  2020-07-01 00:00:01.3620  2020-07-01 00:05:22.9490
2                2710  2020-07-01 00:00:06.6290  2020-07-01 00:45:17.3410
3                2685  2020-07-01 00:00:13.0220  2020-07-01 00:44:58.8640
4                 191  2020-07-01 00:00:13.4660  2020-07-01 00:03:24.6230
...               ...                       ...                       ...
3346399          1587  2020-01-31 23:59:26.8820  2020-02-01 00:25:54.4890
3346400           222  2020-01-31 23:59:32.6410  2020-02-01 00:03:15.4720
3346401           163  2020-01-31 23:59:39.1780  2020-02-01 00:02:23.0400
3346402           327  2020-01-31 23:59:49.2310  2020-02-01 00:05:16.3790
3346403           484  2020-01-31 23:59:57.0360  2020-02-01 00:08:01.1820

         start station id          start station name  start station latitude  \
0                    3463         E 16 St & Irving Pl               40.735367
1                    3463         E 16 St & Irving Pl               40.735367
2                     426       West St & Chambers St               40.717548
3                     426       West St & Chambers St               40.717548
4                    3615               44 Dr & 21 St               40.748000
...                   ...                         ...                     ...
3346399              3244      University Pl & E 8 St               40.731437
3346400               383  Greenwich Ave & Charles St               40.735238
3346401               150           E 2 St & Avenue C               40.720874
3346402               483             E 12 St & 3 Ave               40.732233
3346403               327    Vesey Pl & River Terrace               40.715338

         start station longitude  end station id            end station name  \
0                     -73.987974            2003             1 Ave & E 18 St
1                     -73.987974            2003             1 Ave & E 18 St
2                     -74.013221             212     W 16 St & The High Line
3                     -74.013221             212     W 16 St & The High Line
4                     -73.946093            3127                9 St & 44 Rd
...                          ...             ...                         ...
3346399               -73.994903            3092           Berry St & N 8 St
3346400               -74.000271             383  Greenwich Ave & Charles St
3346401               -73.980858             411           E 6 St & Avenue D
3346402               -73.988900            3718          E 11 St & Avenue B
3346403               -74.016584             534     Water - Whitehall Plaza

         end station latitude  end station longitude  bikeid    usertype  \
0                   40.733812             -73.980544   33861  Subscriber
1                   40.733812             -73.980544   31233  Subscriber
2                   40.743349             -74.006818   40329    Customer
3                   40.743349             -74.006818   17567  Subscriber
4                   40.749660             -73.952100   43421  Subscriber
...                       ...                    ...     ...         ...
3346399             40.719009             -73.958525   40662  Subscriber
3346400             40.735238             -74.000271   28722  Subscriber
3346401             40.722281             -73.976687   32530  Subscriber
3346402             40.727464             -73.979504   15314    Customer
3346403             40.702551             -74.012723   30947  Subscriber

         birth year  gender zip code               timestamp        date  \
0              1986       1    10003 2020-07-01 00:00:01.302  2020-07-01
1              1990       2    10003 2020-07-01 00:00:01.362  2020-07-01
2              1969       0    10282 2020-07-01 00:00:06.629  2020-07-01
3              1998       1    10282 2020-07-01 00:00:13.022  2020-07-01
4              1992       1    11101 2020-07-01 00:00:13.466  2020-07-01
...             ...     ...      ...                     ...         ...
3346399        1990       1      NaN 2020-01-31 23:59:26.882  2020-01-31
3346400        1983       1      NaN 2020-01-31 23:59:32.641  2020-01-31
3346401        1958       2      NaN 2020-01-31 23:59:39.178  2020-01-31
3346402        1994       1      NaN 2020-01-31 23:59:49.231  2020-01-31
3346403        1987       1      NaN 2020-01-31 23:59:57.036  2020-01-31

         month  year
0            7  2020
1            7  2020
2            7  2020
3            7  2020
4            7  2020
...        ...   ...
3346399      1  2020
3346400      1  2020
3346401      1  2020
3346402      1  2020
3346403      1  2020

[3346404 rows x 20 columns]

In [ ]:
data_sets = ['202002-citibike-tripdata.csv', '202003-citibike-tripdata.csv', '202004-citibike-tripdata.csv', '202005-citibike-tripdata.csv', '202006-citibike-tripdata.csv', '202008-citibike-tripdata.csv', '202009-citibike-tripdata.csv', '202010-citibike-tripdata.csv', '202011-citibike-tripdata.csv', '202012-citibike-tripdata.csv']
#data_sets = ['202002-citibike-tripdata.csv']

for set in data_sets: 
    citibike_data = pd.read_csv(set)
    st_r = set
    f_n = st_r.split("-")
    file_name = f_n[0][0 : 2 : ] + f_n[0][4 : :]
    file_str = "_data.csv"
    file_name += file_str
    print(file_name)
        
    citibike_data['timestamp'] = pd.to_datetime(citibike_data['starttime'])
    citibike_data['date'] = [dt.datetime.date(d) for d in citibike_data['timestamp']]
    citibike_data['month'] = pd.DatetimeIndex(citibike_data['timestamp']).month
    citibike_data['year'] = pd.DatetimeIndex(citibike_data['timestamp']).year

    citibike_data.to_csv(file_name)

    frames = [concat_data, citibike_data]
    concat_data = pd.concat(frames).reset_index()
    del concat_data['index']
    print(len(concat_data))

print(concat_data)
citi_grouped = concat_data[["tripduration", "start station latitude", "start station longitude", "zip code", "year"]].groupby([concat_data["start station name"],concat_data["month"]]).agg({"tripduration": ["count", "sum", "min", "max", "mean", "median", "skew"], "start station latitude": ["first"], "start station longitude": ["first"], "zip code": ["first"], "year": ["first"]}).reset_index()
citi_grouped.columns = ['start station name', 'month', 'trip count', 'sum duration', 'min duration', 'max duration', 'mean duration', 'median duration', 'skew', 'start station latitude', 'start station longitude', 'zip code', 'year']

zips = pd.read_csv("zip_code_file.csv")
stations = zips['start station name']
for station in stations:
    df = zips[zips['start station name'] == station]
    zip_data = df.iloc[0]['zip code'] 
    citi_grouped.loc[(citi_grouped['start station name'] == station), 'zip code'] = zip_data
        
citi_grouped.to_csv("2020_groupedByMonth_data.csv")
print (citi_grouped)

2002_data.csv
4493234
2003_data.csv
5561691
2004_data.csv
6244453
2005_data.csv
7732343
2006_data.csv